CREATE TABLE coleta_material (
	ID_COLETA_MATERIAL INT NOT NULL AUTO_INCREMENT,
	QT_MATERIAL INT NOT NULL,
	ID_MATERIAL INT NOT NULL,
	ID_COLETA INT NOT NULL,
	PRIMARY KEY (ID_COLETA_MATERIAL),
	CONSTRAINT fk_COLETA_MATERIAL_MATERIAL1 FOREIGN KEY (ID_MATERIAL) REFERENCES material (ID_MATERIAL),
	CONSTRAINT fk_COLETA_MATERIAL_COLETA1 FOREIGN KEY (ID_COLETA) REFERENCES coleta (ID_COLETA)
);
