CREATE TABLE usuario (
	ID_USUARIO INT UNSIGNED NOT NULL AUTO_INCREMENT,
	NM_USUARIO VARCHAR(100) NOT NULL,
	NR_CPF_CNPJ CHAR(18) NOT NULL,
	DS_EMAIL VARCHAR(100) NOT NULL UNIQUE,
	DS_SENHA VARCHAR(2000) NOT NULL,
	NR_CELULAR CHAR(16) NOT NULL,
	DT_NASCIMENTO DATE NOT NULL,
	ID_ENDERECO INT NOT NULL,
	IC_ATIVO BIT(1) DEFAULT b'1' NOT NULL,
	PRIMARY KEY (ID_USUARIO),
	CONSTRAINT fk_USUARIO_ENDERECO1 FOREIGN KEY (ID_ENDERECO) REFERENCES endereco (ID_ENDERECO)
);
