CREATE TABLE coleta (
	ID_COLETA INT NOT NULL AUTO_INCREMENT,
	DT_COLETA DATE NOT NULL,
	CD_PERIODO ENUM('M', 'T', 'N') NOT NULL,
	ID_USUARIO INT UNSIGNED NOT NULL,
	PRIMARY KEY (ID_COLETA),
	CONSTRAINT fk_COLETA_USUARIO1 FOREIGN KEY (ID_USUARIO) REFERENCES usuario (ID_USUARIO)
);
